[package]
name = "rust-blog"
version = "0.1.0"
authors = ["Yousuf Nejati"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-beta.2"
env_logger = "0.6"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
diesel = { version = "^1.1.0", features = ["sqlite", "r2d2"] }
dotenv = "0.10"
